#!/bin/bash
set -euo pipefail

# ---

echo "Installing dependencies..."

sudo pacman -S --noconfirm base-devel git openssh tar rustup

# ---

echo "Setting up Rust..."

rustup default stable
rustup-init
rustup toolchain install nightly

# ---

echo "Cloning and building Paru..."

git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si --noconfirm

# ---

echo "Installing Chezmoi..."

paru -S --noconfirm chezmoi

# ---

echo "Cleaning up..."

cd ..
rm -rf ~/paru
